name = "remagstyle-payments"
main = "payment-worker.js"
compatibility_date = "2026-09-29"
workers_dev = true
routes = [
  { pattern = "remag.style/api/payments/*", zone_name = "remag.style" }
]

[vars]
FIREBASE_PROJECT_ID = "remagstyle-43b41"
FIREBASE_API_KEY = "AIzaSyCzcxTLAUH83sQsia4dPg5py19YzRsmw0o"
SITE_ORIGIN = "https://remag.style"
PAYSTACK_CALLBACK_URL = "https://remag.style/track-order.html"